### ISSUE TITLE
Vertical ProgressBar

### ISSUE THREAD

**Issue by vsavdeev** [GeniusRUS/MultiProgressBar#10]
It will be so cool to add vertical segmented progress bar feature with good positioning methods.
<img width="424" alt="Screenshot 2021-05-14 at 13 19 33" src="https://user-images.githubusercontent.com/48546873/118257218-0ae92b00-b4b7-11eb-8a7d-2f666f5e93ca.png">

**Comment by GeniusRUS** [comment]
@vsavdeev you can check updated 1.3.0 version

**Comment by AdrisMalik92** [comment]
Can I change the Orientation programmatically?

**Comment by GeniusRUS** [comment]
@AdrisMalik92 support of this feature has been added in commit https://github.com/GeniusRUS/MultiProgressBar/commit/d35a2371bf5e43af47d49926d1db8e87a32e87ba, and will be available in next release

Thank you for your feedback!
