### ISSUE TITLE
infinite onProgressStepChange listener getting called

### ISSUE THREAD

**Issue by prafulSetblue** [GeniusRUS/MultiProgressBar#12]
Hi! I have used this lib for storyview . I m pausing progress by Pause(). the progress gets stopped but listener **onProgressStepChange**
getting called infinitely .

**Comment by GeniusRUS** [comment]
Hi!
Thanks for the report
I'm faced the similar issue recently and update library to `1.3.2` version. Please checkout this and check if the same behavior persists

**Comment by GeniusRUS** [comment]
Fixed in release [1.4.0](https://github.com/GeniusRUS/MultiProgressBar/releases/tag/1.4.0)
