### ISSUE TITLE
Error: app:mergeDebugResources with 1.3.2

### ISSUE THREAD

**Issue by berkayakin** [GeniusRUS/MultiProgressBar#14]
Hi, I get the following error after upgrading to the latest version:

`C:\Users\Berkay\.gradle\caches\transforms-3\5063c25f54dd39ab93da5c2c45d537f8\transformed\jetified-multiprogressbar-1.3.2\res\values\values.xml:2:4: Duplicate value for resource 'attr/orientation' with config 'DEFAULT' and product ''. Resource was previously defined here: C:\Users\Berkay\.gradle\caches\transforms-3\69c8cf232639d37839668622660fc7a4\transformed\gridlayout-1.0.0\res\values\values.xml:2:4: .`

I think the attributes conflict with the ones from the GridLayout library.

**Comment by GeniusRUS** [comment]
Hi! Thanks for the issue, I'll fix it in the next release
The attribute name will be changed to be more specific.

**Comment by GeniusRUS** [comment]
Fixed in release [1.4.0](https://github.com/GeniusRUS/MultiProgressBar/releases/tag/1.4.0)

**Comment by berkayakin** [comment]
Thanks!
