### ISSUE TITLE
Does not work if animation is disabled

### ISSUE THREAD

**Issue by AlexanderShtanko** [GeniusRUS/MultiProgressBar#9]
When animation is disabled in developer options, it does not work properly.

**Comment by ubuntudroid** [comment]
Workaround: https://stackoverflow.com/questions/64226137/ignore-developers-settings-animation-scale-in-android/67108601#67108601

**Comment by ubuntudroid** [comment]
However the actual fix would be not to rely on an animator at all to keep track and update the state, but use coroutines or some other means of timer handling and just update the UI and the callbacks based on that.

**Comment by GeniusRUS** [comment]
Fixed in release [1.4.0](https://github.com/GeniusRUS/MultiProgressBar/releases/tag/1.4.0)
